import { SportEvent, Service, Package, Testimonial, Stat } from '@/types';

export const events: SportEvent[] = [
  {
    id: 'evt-1',
    title: 'Marathon CDMX',
    sport: 'carrera',
    date: '2026-05-15',
    location: 'Ciudad de México',
    capacity: 5000,
    price: 1500,
    image: 'https://picsum.photos/seed/marathon/600/400',
    description: 'El maratón más importante de Latinoamérica. Recorre 42km por las calles más emblemáticas de la CDMX con apoyo profesional en cada kilómetro.',
  },
  {
    id: 'evt-2',
    title: 'Triatlón Vallarta',
    sport: 'triatlon',
    date: '2026-06-20',
    location: 'Puerto Vallarta, Jalisco',
    capacity: 1200,
    price: 2800,
    image: 'https://picsum.photos/seed/triathlon/600/400',
    description: 'Triatlón olímpico frente a las playas de Vallarta. Nado en mar abierto, ciclismo costero y carrera con vista al Pacífico.',
  },
  {
    id: 'evt-3',
    title: 'Ciclismo Monterrey',
    sport: 'ciclismo',
    date: '2026-07-10',
    location: 'Monterrey, Nuevo León',
    capacity: 3000,
    price: 1200,
    image: 'https://picsum.photos/seed/cycling/600/400',
    description: 'Gran Fondo de 120km por la Sierra Madre. Ruta desafiante con ascensos técnicos y descensos espectaculares.',
  },
  {
    id: 'evt-4',
    title: 'Natación Guadalajara',
    sport: 'natacion',
    date: '2026-08-05',
    location: 'Guadalajara, Jalisco',
    capacity: 800,
    price: 900,
    image: 'https://picsum.photos/seed/swimming/600/400',
    description: 'Competencia de natación en aguas abiertas en la Laguna de Chapala. Categorías desde 1.5km hasta 10km.',
  },
  {
    id: 'evt-5',
    title: 'Crossfit Open Nacional',
    sport: 'crossfit',
    date: '2026-09-12',
    location: 'Cancún, Quintana Roo',
    capacity: 2000,
    price: 2200,
    image: 'https://picsum.photos/seed/crossfit/600/400',
    description: 'El open nacional de Crossfit más grande de México. Tres días de competencia intensa con los mejores atletas del país.',
  },
];

export const services: Service[] = [
  {
    id: 'srv-1',
    title: 'Masaje Deportivo Terapéutico',
    description: 'Tratamiento especializado para aliviar tensiones musculares profundas y mejorar la flexibilidad. Ideal para preparación pre-competencia.',
    price: 800,
    priceUnit: 'sesión',
    icon: 'massage',
  },
  {
    id: 'srv-2',
    title: 'Masaje de Recuperación Post-Evento',
    description: 'Recuperación muscular acelerada después de competencias intensas. Reduce inflamación y acelera la regeneración tisular.',
    price: 650,
    priceUnit: 'sesión',
    icon: 'recovery',
  },
  {
    id: 'srv-3',
    title: 'Mantenimiento Físico Mensual',
    description: 'Plan integral mensual con 4 sesiones de mantenimiento, seguimiento personalizado y programa de ejercicios complementarios.',
    price: 2400,
    priceUnit: 'mes',
    icon: 'plan',
  },
  {
    id: 'srv-4',
    title: 'Evaluación Biomecánica',
    description: 'Análisis completo de tu mecánica de movimiento con tecnología de captura de movimiento. Incluye reporte detallado y recomendaciones.',
    price: 1200,
    priceUnit: 'evaluación',
    icon: 'biomechanics',
  },
  {
    id: 'srv-5',
    title: 'Nutrición Deportiva',
    description: 'Consulta personalizada con nutriólogo deportivo certificado. Plan alimenticio adaptado a tu disciplina y objetivos.',
    price: 900,
    priceUnit: 'consulta',
    icon: 'nutrition',
  },
  {
    id: 'srv-6',
    title: 'Fisioterapia de Alto Rendimiento',
    description: 'Sesión de fisioterapia con equipamiento de última generación. Tratamiento de lesiones y prevención con enfoque deportivo.',
    price: 1100,
    priceUnit: 'sesión',
    icon: 'physio',
  },
];

export const packages: Package[] = [
  {
    id: 'pkg-1',
    name: 'Deportista',
    monthlyPrice: 1499,
    annualPrice: 14389,
    features: [
      { text: 'Acceso a 3 eventos por año', included: true },
      { text: '1 servicio de masaje mensual', included: true },
      { text: 'Evaluación biomecánica anual', included: true },
      { text: 'Descuento 10% en servicios', included: true },
      { text: 'Nutrición deportiva', included: false },
      { text: 'Fisioterapia ilimitada', included: false },
      { text: 'Acceso VIP a eventos', included: false },
      { text: 'Coaching personalizado', included: false },
    ],
    cta: 'Contratar',
  },
  {
    id: 'pkg-2',
    name: 'Equipo',
    monthlyPrice: 3499,
    annualPrice: 33590,
    popular: true,
    features: [
      { text: 'Acceso a 8 eventos por año', included: true },
      { text: '4 servicios de masaje mensuales', included: true },
      { text: 'Evaluación biomecánica semestral', included: true },
      { text: 'Descuento 25% en servicios', included: true },
      { text: 'Nutrición deportiva mensual', included: true },
      { text: 'Fisioterapia 2x/mes', included: true },
      { text: 'Acceso VIP a eventos', included: false },
      { text: 'Coaching personalizado', included: false },
    ],
    cta: 'Contratar',
  },
  {
    id: 'pkg-3',
    name: 'Corporativo',
    monthlyPrice: 8999,
    annualPrice: 86390,
    features: [
      { text: 'Acceso ilimitado a eventos', included: true },
      { text: 'Servicios de masaje ilimitados', included: true },
      { text: 'Evaluación biomecánica trimestral', included: true },
      { text: 'Descuento 40% en servicios', included: true },
      { text: 'Nutrición deportiva semanal', included: true },
      { text: 'Fisioterapia ilimitada', included: true },
      { text: 'Acceso VIP a eventos', included: true },
      { text: 'Coaching personalizado', included: true },
    ],
    cta: 'Contratar',
  },
];

export const testimonials: Testimonial[] = [
  {
    id: 'test-1',
    name: 'Carlos Mendoza',
    sport: 'Maratón',
    avatar: 'https://picsum.photos/seed/athlete1/100/100',
    rating: 5,
    quote: 'ÉLITE SPORT transformó mi experiencia competitiva. La organización es impecable y los servicios de recuperación me permitieron superar mis marcas personales.',
  },
  {
    id: 'test-2',
    name: 'María Fernanda López',
    sport: 'Triatlón',
    avatar: 'https://picsum.photos/seed/athlete2/100/100',
    rating: 5,
    quote: 'El triatlón en Vallarta fue una experiencia inolvidable. Cada detalle estaba perfectamente cuidado, desde la logística hasta la recuperación post-evento.',
  },
  {
    id: 'test-3',
    name: 'Roberto Jiménez',
    sport: 'Ciclismo',
    avatar: 'https://picsum.photos/seed/athlete3/100/100',
    rating: 5,
    quote: 'Como ciclista profesional, valoro mucho la calidad de las rutas y la seguridad. ÉLITE SPORT cumple en ambos aspectos al 100%.',
  },
  {
    id: 'test-4',
    name: 'Ana García Vega',
    sport: 'Natación',
    avatar: 'https://picsum.photos/seed/athlete4/100/100',
    rating: 4,
    quote: 'La competencia de natación en Chapala superó todas mis expectativas. El equipo de ÉLITE SPORT realmente entiende las necesidades de los atletas.',
  },
  {
    id: 'test-5',
    name: 'Diego Ramírez',
    sport: 'Crossfit',
    avatar: 'https://picsum.photos/seed/athlete5/100/100',
    rating: 5,
    quote: 'El Crossfit Open Nacional fue brutal en el mejor sentido. Competencia de primer nivel con atletas increíbles. ¡Nos vemos el próximo año!',
  },
  {
    id: 'test-6',
    name: 'Valentina Torres',
    sport: 'Maratón',
    avatar: 'https://picsum.photos/seed/athlete6/100/100',
    rating: 5,
    quote: 'Los servicios de fisioterapia y nutrición marcaron la diferencia en mi preparación. ÉLITE SPORT es mucho más que eventos, es un ecosistema completo.',
  },
  {
    id: 'test-7',
    name: 'Andrés Morales',
    sport: 'Triatlón',
    avatar: 'https://picsum.photos/seed/athlete7/100/100',
    rating: 4,
    quote: 'Desde que me uní al plan Equipo, mi rendimiento ha mejorado un 30%. La evaluación biomecánica fue un antes y después en mi carrera.',
  },
  {
    id: 'test-8',
    name: 'Sofía Hernández',
    sport: 'Ciclismo',
    avatar: 'https://picsum.photos/seed/athlete8/100/100',
    rating: 5,
    quote: 'Como patrocinadora corporativa, puedo decir que la calidad de producción de los eventos de ÉLITE SPORT está al nivel de las mejores marcas internacionales.',
  },
];

export const stats: Stat[] = [
  { value: 120, suffix: '+', label: 'Eventos organizados' },
  { value: 15000, suffix: '+', label: 'Atletas registrados' },
  { value: 8, suffix: '', label: 'Estados de la República' },
  { value: 98, suffix: '%', label: 'Satisfacción' },
];

export const galleryImages = [
  { src: 'https://picsum.photos/seed/sport1/600/800', category: 'Maratón' },
  { src: 'https://picsum.photos/seed/sport2/600/600', category: 'Ciclismo' },
  { src: 'https://picsum.photos/seed/sport3/600/900', category: 'Natación' },
  { src: 'https://picsum.photos/seed/sport4/600/700', category: 'Crossfit' },
  { src: 'https://picsum.photos/seed/sport5/600/500', category: 'Triatlón' },
  { src: 'https://picsum.photos/seed/sport6/600/800', category: 'Maratón' },
  { src: 'https://picsum.photos/seed/sport7/600/600', category: 'Ciclismo' },
  { src: 'https://picsum.photos/seed/sport8/600/750', category: 'Natación' },
  { src: 'https://picsum.photos/seed/sport9/600/650', category: 'Crossfit' },
  { src: 'https://picsum.photos/seed/sport10/600/800', category: 'Triatlón' },
  { src: 'https://picsum.photos/seed/sport11/600/550', category: 'Maratón' },
  { src: 'https://picsum.photos/seed/sport12/600/700', category: 'Ciclismo' },
];
